[pytest]
DJANGO_SETTINGS_MODULE = calendar_admin.settings
pythonpath = calendar_admin
python_files = tests.py test_*.py *_tests.py
asyncio_mode = auto
addopts = -p no:cacheprovider
testpaths = calendar_admin/events/tests
django_find_project = true