# Generated by Django 6.0.3 on 2026-03-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('edited_events', models.PositiveIntegerField(default=0)),
                ('cancelled_events', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статистика бота',
                'verbose_name_plural': 'Статистика бота',
            },
        ),
    ]
