# Generated by Django 6.0.3 on 2026-03-16 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_botstatistics_options_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botstatistics',
            options={'verbose_name': 'Статистика бота', 'verbose_name_plural': 'Статистика бота'},
        ),
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.IntegerField(default=0, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('events_created', models.PositiveIntegerField(default=0, verbose_name='Создано событий')),
                ('events_edited', models.PositiveIntegerField(default=0, verbose_name='Отредактировано')),
                ('events_deleted', models.PositiveIntegerField(default=0, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль Telegram',
                'verbose_name_plural': 'Профили Telegram',
            },
        ),
    ]
