# Generated by Django 6.0.3 on 2026-03-16 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_botstatistics_options_event_details_event_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Встреча', 'verbose_name_plural': 'Встречи'},
        ),
        migrations.AlterModelOptions(
            name='botstatistics',
            options={'ordering': ['-date'], 'verbose_name': 'Статистика бота', 'verbose_name_plural': 'Статистика бота'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='telegramprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль Telegram', 'verbose_name_plural': 'Профили Telegram'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичное событие'),
        ),
        migrations.AlterField(
            model_name='botstatistics',
            name='cancelled_events',
            field=models.PositiveIntegerField(default=0, verbose_name='Отменено событий'),
        ),
        migrations.AlterField(
            model_name='botstatistics',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='botstatistics',
            name='edited_events',
            field=models.PositiveIntegerField(default=0, verbose_name='Отредактировано событий'),
        ),
        migrations.AlterField(
            model_name='botstatistics',
            name='event_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Создано событий'),
        ),
        migrations.AlterField(
            model_name='botstatistics',
            name='user_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Новых пользователей'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django'),
        ),
    ]
